---
image:
  file: .gitpod.Dockerfile
# Commands to start on workspace startup
tasks:
  - init: |
      pnpm install
      pnpm run build
    command: |
      [[ ! -z "$ASTRO_NEW" ]] && gp await-port 23000 && cd "$GITPOD_REPO_ROOT"/examples/"$ASTRO_NEW" && code src/pages/index.astro && pnpm start
vscode:
  extensions:
    - astro-build.astro-vscode
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
ports:
  - port: 3000
    onOpen: open-preview
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
