name: "\U0001F41B Bug Report"
description: Report an issue or possible bug
title: "\U0001F41B "
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.
  - type: checkboxes
    options:
      - label: I am on the **latest version of Astro** and all plugins.
        required: true
      - label: I am using a version of Node that supports ESM (`v12.20.0+`, `v14.13.1+`, or `v16.0.0+`)
        required: true
  - type: dropdown
    attributes:
      label: What package manager are you using?
      options:
        - npm@6
        - npm@7
        - yarn@1
        - yarn@2
        - pnpm
        - other
  - type: input
    attributes:
      label: What operating system are you using?
      description: 'For example: macOS, Windows'
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: "We can't fix bugs that we can't see for ourselves! Issues often need to be closed if this section is skipped."
      value:
        1. `npm init astro` using template <NAME>
        
        2. ...
        
        3. ...
        
        4. ...
        
        5. Error! Describe what went wrong...
