name: Changeset

on:
  pull_request:
    branches:
      - main

jobs:
  release:
    name: Ensure changeset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn --frozen-lockfile
        env:
          CI: true

      - run: changeset status --sinceMaster
