name: Changelog

on:
  push:
    paths-ignore:
      - '.vscode/**'
      - 'assets/**'
      - 'docs/**'
      - 'examples/**'
      - 'www/**'
    branches:
        - main
    

jobs:
  release:
    name: Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn --frozen-lockfile
        env:
          CI: true

      - name: Create Release Pull Request
        uses: changesets/action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
