name: "Discord:congratsbot"

on:
  push:
    branches:
      - main

jobs:
  congrats:
    name: "discord:congratsbot"
    #if: github.event.commits[0] && !github.event.commits[1]
    runs-on: ubuntu-latest
    steps:
      - name: Send a Discord notification when a PR is merged
      
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_CONGRATS }}
          # DISCORD_AVATAR: ${{ github.event.pull_request.user.avatar_url }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: '**Sweet!** ${{ github.event.commits[0].author.name }} just merged ["${{ github.event.commits[0].message }}"](<${{github.event.repository.commits_url}}>)'
