name: "Discord:congratsbot"

on:
  push:
    branches:
      - main

jobs:
  congrats:
    name: "discord:congratsbot"
    if: github.repository == 'snowpackjs/astro'
    runs-on: ubuntu-latest
    steps:
      - id: setup
        run:  |
              TRIMMED=$(echo "${{ github.event.commits[0].message }}" | sed '1!d;q')
              echo "::set-output name=COMMIT_MSG::${TRIMMED}" 
      - name: Send a Discord notification when a PR is merged
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_CONGRATS }}
          # DISCORD_AVATAR: ${{ github.event.pull_request.user.avatar_url }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: '**Sweet!** <${{ github.event.commits[0].author.name }}> just merged ["\"${{ steps.setup.outputs.COMMIT_MSG }}\""](<https://github.com/snowpackjs/astro/commits/main>) ```${{ github.event.commits[0].message }}```'
